name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  verificar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4.2.2

      - name: validar docker-compose.yml
        run: docker compose config